
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - modverify: go mod verify
            - gofmt: if [[ -n "$(gofmt -l .)" ]]; then echo "gofmt check fails"; gofmt -d .; exit -1; fi
            - build: GOBIN="$SD_ARTIFACTS_DIR" go install -v ./...
            - test: go test -v ./...

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get: go get -t ./...
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
