
shared:
    image: golang
    environment:
        GO111MODULE: on

jobs:
    main:
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~commit, ~pr]
        steps:
            - modverify: go mod verify
            - gofmt: if [[ -n "$(gofmt -l .)" ]]; then echo "gofmt check fails"; gofmt -d .; exit -1; fi
            - build: GOBIN="$SD_ARTIFACTS_DIR" go install -v ./...
            - test-setup: go get gotest.tools/gotestsum@v0.6.0
            - test: gotestsum --format testname --jsonfile ${SD_ARTIFACTS_DIR}/report.json -- -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out ./...

    publish:
        requires: [main]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get: go get -t ./...
            - tag: ./ci/git-tag.sh
            - release: "curl -sL https://git.io/goreleaser | bash"
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
